name: flutter_bloc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
